apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tfjob-flat
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: gcr.io/ubuntu-os-support/davecore-financialtimeseries/cpu:v1
            command:
              - python
              - run_preprocess_train_deploy.py
              - --model=FlatModel
              - --epochs=30001
              - --bucket=davecorefinancialtimeseries
              - --tag=v1
            workingDir: "/opt/workdir"
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcp-credentials/user-gcp-sa.json"
            volumeMounts:
            - name: sa
              mountPath: "/secret/gcp-credentials"
              readOnly: true
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa
